CREATE TABLE AccessType (
	ID INTEGER PRIMARY KEY,
	Name VARCHAR(150),
	Details VARCHAR(150),
	AddProduct BOOLEAN,
	ViewProduct BOOLEAN,
);

CREATE TABLE UserInfo (
	ID INTEGER PRIMARY KEY,
	TypeID INTEGER REFERENCES AccessType(ID),
	Email VARCHAR(100) NOT NULL,
	FirstName VARCHAR(60) NOT NULL,
	LastName VARCHAR(60) NOT NULL,	
	PhoneNumber LONG NOT NULL,
	Address VARCHAR(230) NOT NULL,
	DateOfBirth DATE,
	Photo BLOB	
);

CREATE TABLE CropsInfo (
	ID INTEGER PRIMARY KEY,
	CatID INTEGER REFERENCES CropCategory(ID),
	Name VARCHAR(150) NOT NULL,
	Link VARCHAR(MAX)
);

CREATE TABLE CropCategory (
	ID INTEGER PRIMARY KEY,
	Name VARCHAR(150) NOT NULL,
	Details VARCHAR(MAX),
	Link VARCHAR(MAX)
);

CREATE TABLE ProductInfo (
	ID INTEGER PRIMARY KEY,
	Name VARCHAR(230) NOT NULL,
	Details VARCHAR(MAX),
	CropID INTEGER REFERENCES CropsInfo(ID),
	Picture BLOB,
	ManufacturingDate DATE,
	ExpiryDate DATE,
);